CREATE TABLE IF NOT EXISTS products (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL CHECK (name <> ''),
    name text NOT NULL CHECK (name <> ''),
    price decimal(10, 2) NOT NULL,
    quantity integer NOT NULL
);

-- list all data in products table
SELECT * FROM products;

-- INSERT TEST DATA FOR products
INSERT INTO products(code, name, price, quantity)
    VALUES ('PRD1', 'PrettyJess', 100, 1);

INSERT INTO products(code, name, price, quantity)
    VALUES ('PRD2', 'Other2', 50, 30);

INSERT INTO products(code, name, price, quantity)
    VALUES ('PRD3', 'Other3', 70, 35);
